/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./src/components/AdminHeader.vue')['default']
    AnimatedLoader: typeof import('./src/components/AnimatedLoader.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ApplicantHeader: typeof import('./src/components/ApplicantHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
